	.ORIG x3000
	LD R6,INI
	LD R0,ADDR
	STI R0,VADD
	STI R6,KBSR
LOOP	LEA R0,SIGN1
	PUTS
	LD R0,ENTER
	OUT
	JSR DELAY
	LEA R0,SIGN2
	PUTS
	JSR DELAY
	LD R0,ENTER
	OUT
	BRnzp LOOP
	HALT
SIGN1	.STRINGZ "ICS   ICS   ICS   ICS   ICS   ICS"
SIGN2	.STRINGZ "   ICS   ICS   ICS   ICS   ICS   "
ENTER	.FILL x0A
INI	.FILL x4000
VADD	.FILL x0180
ADDR	.FILL x2000
KBSR	.FILL xFE00

DELAY   ST  R1, SaveR1        	
	LD  R1, COUNT
REP  	ADD R1,R1,#-1
	BRp REP       		
	LD  R1, SaveR1
        RET
COUNT   .FILL #2500
SaveR1  .BLKW 1
	.END